version: '3.9'
services:
  postgres:
    container_name: myapp-db
    image: postgres:15.1
    ports:
      - '5431:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./apps/api/docker.env
    networks:
      - postgres

  app:
    container_name: myapp
    build:
      context: .
    image: myapp:latest
    
    env_file:
      - ./apps/api/.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - postgres
  
networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:

